### PR TITLE
Add gRPC gateway reverse proxies for Telemetry Service

### PR DESCRIPTION
**Pull request by ddz**

### CODE REVIEW

**Comment by GrantSeltzer** [comment]
@ddz I'm confused, why did you remove all constraints from `Gopkg.toml`?

**Comment by travertischio** [comment]
When I ran `dep ensure` there was no change. It looks like all of those constraints were on master or on the most recent version that hasn't changed

**Comment by GrantSeltzer** [comment]
`dep ensure` doesn't at all change `Gopkg.toml`, but rather checks it for constraints to populate `vendor` and `Gopkg.lock`. 

The way this is now, all of the dependencies that were removed will possibly be upgraded on any `dep ensure`.

**Comment by travertischio** [comment]
Right, what I am saying is nothing changed because the constraints were all either on `master` or seemingly on a version that is still the most recent update

**Comment by GrantSeltzer** [comment]
Ah, gotcha. Yea that'll change eventually.

**Comment by ddz** [comment]
@GrantSeltzer: Yes, we had a large number of spurious constraints in the manifest. As I understand it, `dep` will upgrade a dependency if it thinks it needs to but it won't aggressively do so if we don't have a version constraint in the manifest. For example, I removed the constraints, ran `dep ensure`, and it didn't upgrade to the latest version of gRPC. If I run `dep ensure -update github.com/grpc/grpc-go`, then it will do so.

**Pull request merged**
