### PR TITLE
fix mounts parsing (#176) and add additional tests

### LINKED ISSUE #176: mounts parsing fails with unbindable mounts on CentOS 7.4 with Docker overlay2 storage driver backed by xfs filesystem
### Is this a bug report or a feature request?

- [X] bug
- [ ] feature

### What is the current behavior?
`make test` fails on pkg/sys in `mount.go`

```
$ make test                               
go test -cover ./cmd/... ./pkg/... ./examples/...  
?       github.com/capsule8/capsule8/cmd/sensor [no test files]
ok      github.com/capsule8/capsule8/pkg/config (cached)        coverage: 78.4% of statements
ok      github.com/capsule8/capsule8/pkg/expression     (cached)        coverage: 67.8% of statements
ok      github.com/capsule8/capsule8/pkg/sensor (cached)        coverage: 4.5% of statements
?       github.com/capsule8/capsule8/pkg/services       [no test files]
ok      github.com/capsule8/capsule8/pkg/stream (cached)        coverage: 48.5% of statements
--- FAIL: TestMounts (0.00s)
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 20 [running]:
testing.tRunner.func1(0xc4200e40f0)
        /usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x524360, 0x6028a0)
        /usr/local/go/src/runtime/panic.go:505 +0x229
github.com/capsule8/capsule8/pkg/sys.readMounts(0x1, 0xc4200a0130, 0x4b58ed)
        /home/dustind/go/src/github.com/capsule8/capsule8/pkg/sys/mount.go:97 +0xd02
github.com/capsule8/capsule8/pkg/sys.Mounts(0xf, 0x5efa85, 0x24)
        /home/dustind/go/src/github.com/capsule8/capsule8/pkg/sys/mount.go:136 +0x2c
github.com/capsule8/capsule8/pkg/sys.TestMounts(0xc4200e40f0)
        /home/dustind/go/src/github.com/capsule8/capsule8/pkg/sys/mount_test.go:24 +0x26
testing.tRunner(0xc4200e40f0, 0x555710)
        /usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:824 +0x2e0
FAIL    github.com/capsule8/capsule8/pkg/sys    0.012s
```

This also makes the sensor start up with this error:
```

$ sudo ./bin/sensor      
I0325 15:03:01.899172    3785 version.go:45] Starting sensor (v0.9.0-alpha+5572748)
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/capsule8/capsule8/pkg/sys.readMounts(0x0, 0xc42006fa00, 0xc42006fac8)
        /home/dustind/go/src/github.com/capsule8/capsule8/pkg/sys/mount.go:97 +0xc3c
github.com/capsule8/capsule8/pkg/sys.Mounts(0xc42023e000, 0xbd, 0x18a)
        /home/dustind/go/src/github.com/capsule8/capsule8/pkg/sys/mount.go:136 +0x22
github.com/capsule8/capsule8/pkg/sys.TracingDir(0x8c8c56, 0x11)
        /home/dustind/go/src/github.com/capsule8/capsule8/pkg/sys/mount.go:207 +0x59
github.com/capsule8/capsule8/pkg/sensor.(*Sensor).Start(0xc4201f0140, 0x0, 0x0)
        /home/dustind/go/src/github.com/capsule8/capsule8/pkg/sensor/sensor.go:128 +0x4ab
github.com/capsule8/capsule8/pkg/sensor.Main()
        /home/dustind/go/src/github.com/capsule8/capsule8/pkg/sensor/main.go:37 +0xba
main.main()
        /home/dustind/go/src/github.com/capsule8/capsule8/cmd/sensor/main.go:32 +0x6e
```

### What is the desired behavior?

Mounts parse correctly and test passes. Sensor starts correctly without panic.

### What version of Capsule8 are you using?
0.9.0 alpha
55727482015d47bc044855bcc91123e0cbbe6289 

### What kind of environment is this in?

What linux distribution are you running?
```
$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
$ uname -r
4.15.12-1.el7.elrepo.x86_64
```

### For bugs: can you share logs?
Yes.

### Other Information

After adding debugging to https://github.com/capsule8/capsule8/blob/master/pkg/sys/mount.go#L96
I have determined that `split()` is being called on the string `unbindable`, and thus the next line causes `panic: runtime error: index out of range`, because there is no index at `tagValue[1]`.
A length check after the split can avoid this, but I suspect that is the wrong fix, and it is just not being parsed correctly right now.

`unbindable` is present in these lines in /proc/self/mountinfo:

```
$ cat /proc/10/mountinfo | grep unbindable
260 89 253:6 /containers/ab63f6eab155cf698a20e7d5e03298dd8baf442ff6e4e20e2dff320f3e2fee3e/mounts /var/lib/docker/containers/ab63f6eab155cf698a20e7d5e03298dd8baf442ff6e4e20e2dff320f3e2fee3e/mounts rw,relatime unbindable - xfs /dev/mapper/rootvg-docker_lv rw,seclabel,attr2,inode64,noquota
193 89 253:6 /containers/7cfb216999bbce04dcf7b0a6a8c4f2ca2706b6953ad5046ff39be13af022a520/mounts /var/lib/docker/containers/7cfb216999bbce04dcf7b0a6a8c4f2ca2706b6953ad5046ff39be13af022a520/mounts rw,relatime unbindable - xfs /dev/mapper/rootvg-docker_lv rw,seclabel,attr2,inode64,noquota
536 89 253:6 /containers/3ace346dd5f78389f0a0d7eef237c651d112c9b63fa4a36618478b0beeea1e32/mounts /var/lib/docker/containers/3ace346dd5f78389f0a0d7eef237c651d112c9b63fa4a36618478b0beeea1e32/mounts rw,relatime unbindable - xfs /dev/mapper/rootvg-docker_lv rw,seclabel,attr2,inode64,noquota
266 89 253:6 /containers/b5da9ad95c6055b735c199c1bf7110d9fc996fe0926b5ee588cba77667e94985/mounts /var/lib/docker/containers/b5da9ad95c6055b735c199c1bf7110d9fc996fe0926b5ee588cba77667e94985/mounts rw,relatime unbindable - xfs /dev/mapper/rootvg-docker_lv rw,seclabel,attr2,inode64,noquota
458 89 253:6 /containers/b3b362a576d6c237483bf49abec77589066965862ab014a7e1fc87723f249517/mounts /var/lib/docker/containers/b3b362a576d6c237483bf49abec77589066965862ab014a7e1fc87723f249517/mounts rw,relatime unbindable - xfs /dev/mapper/rootvg-docker_lv rw,seclabel,attr2,inode64,noquota
288 89 253:6 /containers/c992bec108c0fd82154a517e7a79685791697c2c5e655ba4a7464579ab739651/mounts /var/lib/docker/containers/c992bec108c0fd82154a517e7a79685791697c2c5e655ba4a7464579ab739651/mounts rw,relatime unbindable - xfs /dev/mapper/rootvg-docker_lv rw,seclabel,attr2,inode64,noquota
795 89 253:6 /containers/a473ca80df2941990ee198b1783b6f7d77b2b065b2997f154691d6a874a63feb/mounts /var/lib/docker/containers/a473ca80df2941990ee198b1783b6f7d77b2b065b2997f154691d6a874a63feb/mounts rw,relatime unbindable - xfs /dev/mapper/rootvg-docker_lv rw,seclabel,attr2,inode64,noquota
```

### PR DESCRIPTION
**Pull request by dustin-decker**
Fixes #176 and adds additional mock mount tests rather than just testing live mounts on the system.

### CODE REVIEW

**Comment by dustin-decker** [comment]
I didn't see any library vendored for object equivalence assertions, so I brought in "github.com/stretchr/testify/assert". I can use whatever you prefer though. The CircleCI test failed because that library is not currently vendored.

**Comment by dustin-decker** [comment]
This is the only new thing: https://github.com/capsule8/capsule8/pull/177/files#diff-e0633ea93615ea93dd86a03befe2d69cR83

Otherwise, I split the parsing functionality out so it's easily testable with mock data.

**Comment by ddz** [comment]
This is great, thank you. It looks like we don't have it documented how to update `capsule8_vendor`, but it's basically:

1. Make sure that `capsule8` is checked out to with submodules as well (`git submodule init && git submodule update)
2. Update vendoring with `dep`
3. Submit a PR to `capsule8_vendor` with the changes (I believe we set up our CLA bot on that too)
4. `capsule8_vendor` PR gets merged to `master`
5. Once vendoring PR is merged, update the `vendor` submodule in your `capsule8` PR to its latest `master`. The vendoring changes should be in a single commit in that PR combining the changes to `Gopkg.toml`, `Gopkg.lock`, and the submodule ref update to `vendor`.
 
You'd be the first to try this outside of our org (but I think you were also our first external PR too), so YMMV. Did you want to try the process above out?

**Comment by dustin-decker** [comment]
Okay, i'll give that process a shot and probably make a PR for adding it to the docs.

**Comment by dustin-decker** [comment]
It looks like `unbindable` is one of a few 'mount propagation types': https://lwn.net/Articles/690679/

I could look at adding parsing for that too if it's valuable.

**Comment by ddz** [comment]
I just approved and merged capsule8/capsule8_vendor#15, so if you update this PR with a submodule ref bump of `vendor/` and the associated updates to `Gopkg.toml` and `Gopkg.lock`, the builds should start passing.

**Comment by ddz** [comment]
Also, :+1: on adding a table-driven test for `Mounts()` (ala https://github.com/golang/go/wiki/TableDrivenTests).

**Comment by dustin-decker** [comment]
I updated the test to be more in line with the table driven test pattern - I had separate structs for Mount and mountLine before which was almost TDT but not quite. Updated the vendoring. Should be good to go now.

**Pull request merged**
